# Copyright 2021 Tom Haddon
# See LICENSE file for licensing details.
options:
  kube-config:
    default: ""
    description: k8s config. If you're using microk8s, this should be the output of `microk8s config`.
    type: string
  service-hostname:
    default: ""
    description: The hostname of the service to create an ingress for.
    type: string
  service-name:
    default: ""
    description: The name of the service to create an ingress for.
    type: string
  service-namespace:
    default: ""
    description: The namespace of the service to create an ingress for. Will default to the namespace this charm is deployed into.
    type: string
  service-port:
    default: 0
    description: The port of the service to create an ingress for.
    type: int
  tls_secret_name:
    default: ""
    description: The name of the TLS secret to use. Leaving this empty will configure an Ingress with TLS disabled.
    type: string
