# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
options:
  ingress-class:
    default: ""
    description: >
      The ingress class annotation to target for this ingress resource. If your
      kubernetes cluster has multiple ingress controllers, this allows you to
      target the correct one. See https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/
      for more details. Leaving empty will mean the "kubernetes.io/ingress.class"
      annotation is unset. This value isn't available to be set via the relation
      as it's a deploy-time configuration item.
    type: string
  kube-config:
    default: ""
    description: k8s config. If you're using microk8s, this should be the output of `microk8s config`.
    type: string
  limit-rps:
    default: 0
    description: >
      Number of requests accepted from a given IP each second. The burst limit
      is set to this limit multiplied by 5. When clients exceed this limit a
      503 error will be returned.
      Setting this to 0 disables rate-limiting.
    type: int
  limit-whitelist:
    default: ""
    description: >
      If rate-limiting is set, client IP source ranges to be excluded. The value
      is a comma-separated list of CIDRs.
    type: string
  max-body-size:
    default: 0
    description: Max allowed body-size (for file uploads) in megabytes, set to 0 to disable limits.
    type: int
  retry-errors:
    default: ""
    description: >
      Specifies in which cases a request should be retried against the next server.
      Comma-separated list, e.g. "error,timeout,http_502,http_503,http_504".
      See http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream
      for more details. Unrecognised values will be ignored. The nginx default
      will be used if this config option is set to an empty value.
    type: string
  service-hostname:
    default: ""
    description: The hostname of the service to create an ingress for.
    type: string
  service-name:
    default: ""
    description: The name of the service to create an ingress for.
    type: string
  service-namespace:
    default: ""
    description: The namespace of the service to create an ingress for. Will default to the namespace this charm is deployed into.
    type: string
  service-port:
    default: 0
    description: The port of the service to create an ingress for.
    type: int
  session-cookie-max-age:
    default: 0
    description: The max age to configure a session cookie for. Leaving unset or setting to 0 will disable session cookies and cookie-based affinity.
    type: int
  tls-secret-name:
    default: ""
    description: The name of the TLS secret to use. Leaving this empty will configure an ingress with TLS disabled.
    type: string
